# Generated by Django 5.0.7 on 2024-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_code',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
