# Generated by Django 5.0.7 on 2024-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_sale_transaction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
